# meta file
---
galaxy_info:
  namespace: oefenweb
  role_name: network_interfaces
  author: Andreas Reischuck
  company: Dresden Weekly
  description: Manage network interfaces in Debian-like systems
  license: MIT
  min_ansible_version: 2.9.0
  platforms:
    - name: Ubuntu
      versions:
        - precise
        - trusty
        - xenial
    - name: Debian
      versions:
        - wheezy
        - jessie
        - stretch
  galaxy_tags:
    - networking
    - system
dependencies: []
