---
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Copyright (C) 2014-2022 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2014-2022 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

- name: Import DebOps global handlers
  import_role:
    name: 'global_handlers'

- name: Install Java packages
  package:
    name: '{{ q("flattened", (java__base_packages
                              + java__jdk_packages
                              + java__packages
                              + java__group_packages
                              + java__host_packages
                              + java__dependent_packages)) }}'
    state: 'present'
  register: java__register_packages
  until: java__register_packages is succeeded

- name: Update Java alternatives
  command: 'update-java-alternatives -s {{ java__alternatives }}'
  when: java__alternatives|d()

- name: Make sure that Ansible local facts directory exists
  file:
    path: '/etc/ansible/facts.d'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: Save Java local facts
  template:
    src: 'etc/ansible/facts.d/java.fact.j2'
    dest: '/etc/ansible/facts.d/java.fact'
    owner: 'root'
    group: 'root'
    mode: '0755'
  notify: [ 'Refresh host facts' ]
  tags: [ 'meta::facts' ]

- name: Update Ansible facts if they were modified
  meta: 'flush_handlers'

- name: Divert default Java security policy configuration file
  dpkg_divert:
    path: '{{ java__security_policy_path }}'
    state: 'present'

- name: Generate default Java security policy configuration
  ansible.builtin.template:
    src: 'etc/java-x-openjdk/security/java.policy.j2'
    dest: '{{ java__security_policy_path }}'
    mode: '0644'
