---
# Copyright (C) 2015-2016 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2015-2021 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

- name: Configure mount points
  import_playbook: 'mount.yml'

- name: Configue network information database
  import_playbook: 'netbase.yml'

- name: Configure sysnews service
  import_playbook: 'sysnews.yml'

- name: Configure kernel modules
  import_playbook: 'kmod.yml'

- name: Configure sysfs attributes
  import_playbook: 'sysfs.yml'

- name: Configure swap files
  import_playbook: 'swapfile.yml'

- name: Configure LVM subsystem
  import_playbook: 'lvm.yml'

- name: Configure NFS server service
  import_playbook: 'nfs_server.yml'

- name: Configure NFS client service
  import_playbook: 'nfs.yml'

- name: Configure gitusers environment
  import_playbook: 'gitusers.yml'

- name: Configure OpenLDAP service
  import_playbook: 'slapd.yml'

- name: Configure nslcd service
  import_playbook: 'nslcd.yml'

- name: Configure nscd service
  import_playbook: 'nscd.yml'

- name: Configure sssd service
  import_playbook: 'sssd.yml'

- name: Configure iSCSI devices
  import_playbook: 'iscsi.yml'

- name: Configure cryptsetup subsystem
  import_playbook: 'cryptsetup.yml'

- name: Configure QubesOS persistent paths
  import_playbook: 'persistent_paths.yml'

- name: Configure external APT repositories
  import_playbook: 'extrepo.yml'

- name: Configure NeuroDebian APT repository
  import_playbook: 'neurodebian.yml'

- name: Configure dropbear SSH server in initramfs
  import_playbook: 'dropbear_initramfs.yml'
