---
# Copyright (C) 2024 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2024 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

- name: Initialize password for user account '{{ item }}'
  ansible.builtin.shell: |
    set -o nounset -o pipefail -o errexit &&
    bin/elasticsearch-reset-password --username {{ item }} --batch --silent
  args:
    executable: 'bash'
    chdir: '/usr/share/elasticsearch'
  register: elasticsearch__register_builtin_password
  changed_when: elasticsearch__register_builtin_password.stdout != ''
  no_log: '{{ debops__no_log | d(True) }}'

- name: Create required directories on Ansible Controller
  ansible.builtin.file:
    path: '{{ secret + "/" + elasticsearch__secret_path + "/" + item }}'
    state: 'directory'
    mode: '0755'
  become: False
  delegate_to: 'localhost'
  when: elasticsearch__register_builtin_password.stdout_lines | d()
  no_log: '{{ debops__no_log | d(True) }}'

- name: Save generated password of account '{{ item }}'
  ansible.builtin.copy:
    content: '{{ elasticsearch__register_builtin_password.stdout }}'
    dest: '{{ secret + "/" + elasticsearch__secret_path + "/" + item + "/password" }}'
    mode: '0644'
  become: False
  delegate_to: 'localhost'
  when: elasticsearch__register_builtin_password.stdout | d()
  no_log: '{{ debops__no_log | d(True) }}'
