---
# Copyright (C) 2017 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2017 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

# Ensure that custom Ansible plugins and modules included in the main DebOps
# collection are available to roles in other collections.
collections: [ 'debops.debops' ]

dependencies: []

galaxy_info:

  company: 'DebOps'
  author: 'Maciej Delmanowski'
  description: 'Manage mail alias database in /etc/aliases'
  license: 'GPL-3.0-only'
  min_ansible_version: '2.3.0'

  platforms:

    - name: Ubuntu
      versions:
        - precise
        - trusty
        - xenial

    - name: Debian
      versions:
        - wheezy
        - jessie
        - stretch

  galaxy_tags:
    - email
    - mail
    - smtp
    - smtpd
    - postfix
