---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker

# Copyright (C) 2015-2016 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2015      Hartmut Goebel <h.goebel@crazy-compilers.com>
# Copyright (C) 2015-2019 Robin Schneider <ypid@riseup.net>
# Copyright (C) 2015-2019 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

- name: Configure ownCloud APT repository
  ansible.builtin.template:
    src: 'etc/apt/sources.list.d/debops_owncloud.list.j2'
    dest: '/etc/apt/sources.list.d/debops_owncloud.list'
    owner: 'root'
    group: 'root'
    mode: '0644'
  register: owncloud__register_apt_repository
  when: (owncloud__variant in ["owncloud"])

- name: Update APT repository cache
  ansible.builtin.apt:  # noqa no-handler
    update_cache: True
  register: owncloud__register_apt_cache
  until: owncloud__register_apt_cache is succeeded
  when: owncloud__register_apt_repository is changed

  ## Use filename when available (2.1.0) https://github.com/ansible/ansible-modules-core/pull/2696
  ## To avoid multiple of those source files.
  ## ypid: Does not help much. When the URL changes, the old source entry will
  ## need to be made absent so stay with the current way.
  ## Disabled because each repository URLs would need to be made absent
  ## manually with using `apt_repository`. If that is solved, then go with
  ## `apt_repository` again.
# - name: Configure ownCloud APT repository
#   ansible.builtin.apt_repository:
#     repo: '{{ owncloud__apt_repo_source }}'
#     state: 'present'
#     update_cache: True

- name: Ensure specified packages are in there desired state
  ansible.builtin.package:
    name: '{{ q("flattened", (owncloud__base_packages
                              + owncloud__packages
                              + owncloud__group_packages
                              + owncloud__host_packages
                              + owncloud__dependent_packages)) }}'
    state: '{{ "absent"
               if (owncloud__deploy_state in ["absent"])
               else ("latest"
                     if (ansible_local | d() and ansible_local.owncloud | d() and
                         ((ansible_local.owncloud.release | d(owncloud__release) != owncloud__release) or
                          (ansible_local.owncloud.auto_security_updates_enabled | d() | bool)))
                     else "present") }}'
  register: owncloud__register_apt_install
  until: owncloud__register_apt_install is succeeded
