apt__repositories:
  - name: 'helm'
    filename: 'helm.list'
    repo: 'deb https://{{ internal_repository_url }}/helm/stable/debian/ all main'
    state: 'present'

  - name: 'kubernetes'
    filename: 'kubernetes.list'
    repo: 'deb https://{{ internal_repository_url }}/kubernetes/core:/stable:/v{{ kunbernetes_version }}/deb/ /'
    state: 'present'

apt_install__packages:
  - 'helm'
  - 'kubectl'

kunbernetes_version: 1.30
