apt__repositories:
  - name: 'helm'
    filename: 'helm.list'
    repo: 'deb https://nexus3.cloud.lab/repository/helm all main'
    state: 'present'

  - name: 'kubernetes'
    filename: 'kubernetes.list'
    repo: 'deb https://nexus3.cloud.lab/kubernetes/core:/stable:/v1.30/deb/ /'
    state: 'present'

apt_install__packages:
  - 'helm'
  - 'kubectl'
