apt__repositories:
  - name: 'helm'
    filename: 'helm.sources'
    uris: 'https://{{ internal_repository_url }}/helm/stable/debian'
    signed_by: 'https://{{ internal_repository_url }}/repository/helm/signing.asc'
    suites: 'all'
    components: 'main'
    state: 'present'

  - name: 'kubernetes'
    filename: 'kubernetes.sources'
    uris: 'https://{{ internal_repository_url }}/kubernetes/core:/stable:/v{{ kunbernetes_version }}/deb'
    signed_by: 'https://{{ internal_repository_url }}/repository/kubernetes/core:/stable:/v{{ kunbernetes_version }}/deb/Release.key'
    state: 'present'

apt_install__packages:
  - 'helm'
  - 'kubectl'

kunbernetes_version: 1.30
