apt__repositories:
  - name: 'docker'
    filename: 'docker.list'
    repo: 'deb https://nexus3.cloud.lab/repository/docker/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable'
    state: 'present'

docker_server__upstream: True

docker_server__packages: 
  - 'docker-buildx-plugin'
  - 'docker-scan-plugin'

docker_server__configuration:
  - name: 'registry-mirrors'
    config:
      'registry-mirrors':
        - 'https://registry.cloud.lab'
    state: 'present'
