apt__repositories:
  - name: 'docker'
    filename: 'docker.sources'
    uris: 'https://{{ internal_repository_url }}/docker/{{ ansible_distribution|lower }}'
    signed_by: 'https://{{ internal_repository_url }}/repository/docker/debian/gpg'
    suites: '{{ ansible_distribution_release }}'
    components: 'stable'
    state: 'present'

docker_server__upstream: True

docker_server__packages: 
  - 'docker-buildx-plugin'
  - 'docker-scan-plugin'

docker_server__configuration:
  - name: 'registry-mirrors'
    config:
      'registry-mirrors':
        - 'https://{{ internal_registry_url }}'
    state: 'present'

internal_registry_url: 'registry.cloud.lab'
