---
# Copyright (C) 2017 Robin Schneider <ypid@riseup.net>
# Copyright (C) 2017 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

# http://kodi.wiki/view/HOW-TO:Autostart_Kodi_for_Linux

- name: Ensure specified packages are in there desired state
  package:
    name: '{{ q("flattened", kodi__base_packages) }}'
    state: '{{ "present" if (kodi__deploy_state == "present") else "absent" }}'
  register: kodi__register_packages
  until: kodi__register_packages is succeeded
  tags: [ 'role::kodi:pkgs' ]

# System user and group [[[
- name: Create Kodi system group
  group:
    name: '{{ kodi__group }}'
    state: '{{ "present" if (kodi__deploy_state == "present") else "absent" }}'
    system: True

- name: Create Kodi system user
  user:
    name: '{{ kodi__user }}'
    group: '{{ kodi__group }}'
    groups: '{{ kodi__groups | join(",") | default(omit) }}'
    append: False
    home: '{{ kodi__home_path }}'
    comment: '{{ kodi__gecos }}'
    shell: '{{ kodi__shell }}'
    state: '{{ "present" if (kodi__deploy_state == "present") else "absent" }}'
    system: True
# ]]]

- name: Create polkit configuration
  template:
    src: 'etc/polkit-1/localauthority/50-local.d/kodi-actions.pkla.j2'
    dest: '/etc/polkit-1/localauthority/50-local.d/kodi-actions.pkla'
    owner: 'root'
    group: 'root'
    mode: '0644'
  when: kodi__polkit_action|d()

- name: Remove polkit configuration
  file:
    path: '/etc/polkit-1/localauthority/50-local.d/kodi-actions.pkla'
    state: 'absent'
  when: not kodi__polkit_action|d()
