# tasks file
---
- name: check version support
  ansible.builtin.fail:
    msg: "HAProxy version {{ haproxy_version }} is not supported"
  when: haproxy_version | string not in haproxy_versions_supported
  tags:
    - configuration
    - haproxy
    - haproxy-check-version-support

- ansible.builtin.import_tasks: install.yml
  tags:
    - configuration
    - haproxy
    - haproxy-install

- ansible.builtin.import_tasks: certificates.yml
  tags:
    - configuration
    - haproxy
    - haproxy-certificates

- ansible.builtin.import_tasks: acl.yml
  tags:
    - configuration
    - haproxy
    - haproxy-acl

- ansible.builtin.import_tasks: configuration.yml
  tags:
    - configuration
    - haproxy
    - haproxy-configuration

- ansible.builtin.import_tasks: letsencrypt.yml
  tags:
    - configuration
    - haproxy
    - haproxy-letsencrypt

- name: start and enable service
  ansible.builtin.service:
    name: haproxy
    state: "{{ service_default_state | default('started') }}"
    enabled: "{{ service_default_enabled | default(true) | bool }}"
  tags:
    - configuration
    - haproxy
    - haproxy-start-enable-service
