---
# Copyright (C) 2016-2017 Robin Schneider <ypid@riseup.net>
# Copyright (C) 2016-2017 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

- name: 'Run bind-dirs'
  ansible.builtin.command: '{{ persistent_paths__qubes_os_handler }}'
  register: persistent_paths__register_bind_dirs
  changed_when: persistent_paths__register_bind_dirs.changed | bool
