---
# Copyright (C) 2019 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2019 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

- name: Configure Filebeat service
  import_playbook: 'filebeat.yml'

- name: Configure Metricbeat service
  import_playbook: 'metricbeat.yml'

- name: Configure GitLab Runner service
  import_playbook: 'gitlab_runner.yml'

- name: Configure Telegraf service
  import_playbook: 'telegraf.yml'

- name: Configure Zabbix Agent
  import_playbook: 'zabbix_agent.yml'
