---
collections:
  - name: debops.debops
    version: 3.2.4

  - name: freeipa.ansible_freeipa
    version: 1.14.5

roles:
  - name: containerd
    src: https://github.com/incubateur-pe/containerd

  - name: mrlesmithjr.netplan
    src: https://github.com/mrlesmithjr/ansible-netplan
    version: v0.4.2

  - name: oefenweb.ca_certificates  
    src: https://github.com/Oefenweb/ansible-ca-certificates
    version: v1.0.49

  - name: oefenweb.dns
    src: https://github.com/Oefenweb/ansible-dns
    version: v1.1.39
    
  - name: oefenweb.ssh_keys
    src: https://github.com/Oefenweb/ansible-ssh-keys
    version: v5.0.5

  - name: oefenweb.user
    src: https://github.com/Oefenweb/ansible-user
    version: v1.1.48
  
  - name: oefenweb.vim
    src: https://github.com/Oefenweb/ansible-vim
    version: v2.0.48
