---
collections:
  - name: debops.debops
    version: 3.1.0

  - name: freeipa.ansible_freeipa
    version: 1.12.1

roles:
# common
  - name: chrony
    src: https://github.com/mrlesmithjr/ansible-chrony

  - name: containerd
    src: https://github.com/incubateur-pe/containerd

  - name: docker
    src: https://github.com/geerlingguy/ansible-role-docker

# debian/ubuntu
  - name: ansible
    src: https://github.com/Oefenweb/ansible-ansible

  - name: apparmor
    src: https://github.com/Oefenweb/ansible-apparmor
  
  - name: bash
    src: https://github.com/Oefenweb/ansible-bash
  
  - name: oefenweb.ca_certificates  
    src: https://github.com/Oefenweb/ansible-ca-certificates
    version: v1.0.47

  - name: oefenweb.dns
    src: https://github.com/Oefenweb/ansible-dns
    version: v1.1.39
    
  - name: fail2ban
    src: https://github.com/Oefenweb/ansible-fail2ban
  
  - name: fonts
    src: https://github.com/Oefenweb/ansible-fonts

  - name: haproxy
    src: https://github.com/Oefenweb/ansible-haproxy
  
  - name: hostname
    src: https://github.com/Oefenweb/ansible-hostname

  - name: keepalived
    src: https://github.com/Oefenweb/ansible-keepalived

  - name: limits
    src: https://github.com/Oefenweb/ansible-limits
  
  - name: locales
    src: https://github.com/Oefenweb/ansible-locales
  
  - name: logrotated
    src: https://github.com/Oefenweb/ansible-logrotated
  
  - name: netplan
    src: https://github.com/Oefenweb/ansible-netplan

  - name: network_interfaces
    src: https://github.com/Oefenweb/ansible-network-interfaces

  - name: nfs_clinet
    src: https://github.com/Oefenweb/ansible-nfs-client
  
  - name: nfs_server
    src: https://github.com/Oefenweb/ansible-nfs-server
  
  - name: ntp
    src: https://github.com/Oefenweb/ansible-ntp

  - name: postfix
    src: https://github.com/Oefenweb/ansible-postfix
  
  - name: rc_local
    src: https://github.com/Oefenweb/ansible-rc-local
  
  - name: rsync_sync
    src: https://github.com/Oefenweb/ansible-rsync-sync
  
  - name: rsyslog
    src: https://github.com/Oefenweb/ansible-rsyslog
  
  - name: ssh_client
    src: https://github.com/Oefenweb/ansible-ssh-client
  
  - name: oefenweb.ssh_keys
    src: https://github.com/Oefenweb/ansible-ssh-keys
    version: v5.0.3

  - name: ssh_server
    src: https://github.com/Oefenweb/ansible-ssh-server

  - name: snmpd
    src: https://github.com/Oefenweb/ansible-snmpd
  
  - name: sudoers
    src: https://github.com/Oefenweb/ansible-sudoers

  - name: swapfile
    src: https://github.com/Oefenweb/ansible-swapfile

  - name: sysctl
    src: https://github.com/Oefenweb/ansible-sysctl
  
  - name: sysfs
    src: https://github.com/Oefenweb/ansible-sysfs
  
  - name: systemd
    src: https://github.com/Oefenweb/ansible-systemd
  
  - name: timezone
    src: https://github.com/Oefenweb/ansible-timezone

  - name: ufw
    src: https://github.com/Oefenweb/ansible-ufw
  
  - name: oefenweb.user
    src: https://github.com/Oefenweb/ansible-user
    version: v1.1.45
  
  - name: oefenweb.vim
    src: https://github.com/Oefenweb/ansible-vim
    version: v2.0.46
