---
# Copyright (C) 2015-2016 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2015-2016 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

- import_playbook: nodejs.yml

- import_playbook: ruby.yml

- import_playbook: golang.yml

- import_playbook: java.yml

- import_playbook: cran.yml

- import_playbook: php.yml

- import_playbook: fcgiwrap.yml

- import_playbook: wpcli.yml
