---
# Copyright (C) 2015-2016 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2015-2016 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

- name: Configure LXC service
  import_playbook: 'lxc.yml'

- name: Configure LXD service
  import_playbook: 'lxd.yml'

- name: Configure Docker Engine service
  import_playbook: 'docker_server.yml'

- name: Configure libvirt daemon service
  import_playbook: 'libvirtd.yml'

- name: Configure libvirt qemu support
  import_playbook: 'libvirtd_qemu.yml'

- name: Configure libvirt client environment
  import_playbook: 'libvirt.yml'
