---
# Copyright (C) 2015-2017 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2015-2017 Robin Schneider <ypid@riseup.net>
# Copyright (C) 2015-2017 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

# Ensure that custom Ansible plugins and modules included in the main DebOps
# collection are available to roles in other collections.
collections: [ 'debops.debops' ]

dependencies: []

galaxy_info:

  company: 'DebOps'
  author: 'Maciej Delmanowski, Robin Schneider'
  description: 'Manage one or multiple sets of Diffie-Hellman Ephemeral parameters'
  license: 'GPL-3.0-only'
  min_ansible_version: '2.2.0'

  platforms:

    - name: Ubuntu
      versions:
        - precise
        - quantal
        - raring
        - saucy
        - trusty

    - name: Debian
      versions:
        - wheezy
        - jessie

  galaxy_tags:
    - encryption
    - security
    - tls
    - ssl
    - pki
    - weakdh
    - logjam
