# tasks file
---
- include: repository.yml
  tags:
    - configuration
    - docker
    - docker-repository

- name: install | dependencies
  apt:
    name: "{{ docker_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
  notify: restart docker
  tags:
    - configuration
    - docker
    - docker-install
    - docker-install-dependencies

- name: configuration | update
  template:
    src: "{{ docker_docker_default_file.lstrip('/') }}.j2"
    dest: "{{ docker_docker_default_file }}"
    owner: root
    group: root
    mode: 0644
  notify: restart docker
  tags:
    - configuration
    - docker
    - docker-configuration
    - docker-configuration-update

- name: start and enable service
  service:
    name: docker
    state: "{{ service_default_state | default('started') }}"
    enabled: "{{ service_default_enabled | default(true) | bool }}"
  tags:
    - configuration
    - docker
    - docker-start-enable-service

- include: ufw.yml
  when: docker_manage_ufw | bool
  tags:
    - configuration
    - docker
    - docker-ufw

- include: updatedb.yml
  when: docker_manage_updatedb
  tags:
    - configuration
    - docker
    - docker-updatedb
