# tasks file
---
- name: updatedb | check file existence
  stat:
    path: "{{ docker_updatedb_file }}"
  register: _updatedb_file_stats
  tags:
    - docker-updatedb-check-file-existence

- name: updatedb | disable indexing of /var/lib/docker
  command: >
    /usr/bin/updatedb -e /var/lib/docker
  when: _updatedb_file_stats.stat.exists
  tags:
    - docker-updatedb-disable-indexing
