---
# Copyright (C) 2015-2017 Robin Schneider <ypid@riseup.net>
# Copyright (C) 2016-2017 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

# Ensure that custom Ansible plugins and modules included in the main DebOps
# collection are available to roles in other collections.
collections: [ 'debops.debops' ]

dependencies: []

galaxy_info:

  company: 'DebOps'
  author: 'Robin Schneider'
  description: 'Setup and manage Foodsoft'
  license: 'GPL-3.0-only'
  min_ansible_version: '2.1.5'

  platforms:

    - name: Debian
      versions:
        - jessie

  galaxy_tags:
    - web
    - foodsoft
    - foodcoop
    - food
    - ordering
