---
# Copyright (C) 2021-2022 Berkhan Berkdemir <berkhan@tekdanisman.com>
# Copyright (C) 2015-2022 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

# Ensure that custom Ansible plugins and modules included in the main DebOps
# collection are available to roles in other collections.
collections: [ 'debops.debops' ]

dependencies: []

galaxy_info:

  author: 'Berkhan Berkdemir'
  description: 'Install and manage a Miniflux instance'
  company: 'DebOps'
  license: 'GPL-3.0-only'
  min_ansible_version: '1.8.0'

  platforms:

    - name: 'Ubuntu'
      versions: [ 'all' ]

    - name: 'Debian'
      versions: [ 'all' ]

  galaxy_tags:
    - cloud
    - private
    - privacy
