---
- name: Converge
  hosts: all
  become: true
  roles:
    - role: ../../../
      when: >
        false
        or (ansible_distribution == 'Debian' and ansible_distribution_major_version is version('10', '>='))
        or (ansible_distribution == 'Ubuntu' and ansible_distribution_major_version is version('18', '>='))
