---
# Copyright (C) 2022 David Härdeman <david@hardeman.nu>
# Copyright (C) 2022 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

# Ensure that custom Ansible plugins and modules included in the main DebOps
# collection are available to roles in other collections.
collections: [ 'debops.debops' ]

dependencies: []

galaxy_info:

  company: 'DebOps'
  author: 'David Härdeman'
  description: 'Configure the BIND DNS server'
  license: 'GPL-3.0-only'
  min_ansible_version: '2.9.0'

  platforms:

    - name: 'Ubuntu'
      versions: [ 'all' ]

    - name: 'Debian'
      versions: [ 'all' ]

  galaxy_tags:
    - bind
    - bind9
    - named
    - dns
