apt__distribution_repository_map:
  'Debian': 'https://nexus3.cloud.lab/repository/debian'

apt__sources:
  - name: 'debian-release-security'
    types: '{{ apt__archive_types }}'
    uri: 'https://nexus3.cloud.lab/repository/debian-security/'
    suites:
      - '{{ apt__distribution_release + "-security" }}'
    components: [ 'main' ]
    state: '{{ "present"
               if (apt__distribution == "Debian" and
                   apt__distribution_release not in apt__debian_archived_releases and
                   apt__distribution_version != "n/a")
               else "ignore" }}'

apt__combined_sources: '{{ apt__debian_sources
                           + apt__sources }}'

apt__repositories:
  - name: 'ceph-v18'
    filename: 'ceph-v18.list'
    repo: 'deb https://nexus3.cloud.lab/repository/ceph/debian-reef/ {{ ansible_distribution_release }} main'
    state: '{{ "present"
               if (ansible_distribution == "Debian" and 
                   ansible_distribution_release in ["bookworm"] and
                   apt__distribution_version != "n/a")
               else "ignore" }}'
  - name: 'ceph-v17'
    filename: 'ceph-v17.list'
    repo: 'deb https://nexus3.cloud.lab/repository/ceph/debian-quincy/ {{ ansible_distribution_release }} main'
    state: '{{ "present"
               if (ansible_distribution == "Debian" and
                   ansible_distribution_release in ["bullseye"] and
                   apt__distribution_version != "n/a")
               else "ignore" }}'

apt__configuration:
  - name: 'verify-peer'
    filename: '99verify-peer.conf'
    raw: |
      Acquire { https::Verify-Peer false }
    state: 'present'
