---
galaxy_info:
  author: Larry Smith Jr.
  description: Ansible role to install/configure Squid Proxy
  license: MIT
  min_ansible_version: "2.8"
  role_name: squid
  namespace: mrlesmithjr

  platforms:
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - networking
    - web

dependencies: []
