apt__repositories:

  - name: 'docker'
    filename: 'docker.list'
    repo: 'deb https://nexus3.cloud.lab/repository/docker/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable'
    state: 'present'
