---
- name: Playbook to manage password policy
  hosts: ipaserver
  become: no
  gather_facts: no

  tasks:
  - name: Set password policy grace limit.
    freeipa.ansible_freeipa.ipapwpolicy:
      ipaadmin_password: SomeADMINpassword
      gracelimit: 3
