---
- name: Playbook to handle sudocmdgroups
  hosts: ipaserver
  become: true

  tasks:
  - name: Ensure sudocmdgroup is absent
    freeipa.ansible_freeipa.ipasudocmdgroup:
      ipaadmin_password: SomeADMINpassword
      name: network
      state: absent
      action: sudocmdgroup
