# meta file
---
galaxy_info:
  namespace: oefenweb
  role_name: netplan
  author: Mischa ter Smitten
  company: Oefenweb.nl B.V.
  description: Set up netplan in Debian-like systems
  license: MIT
  min_ansible_version: 2.9.0
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - focal
    - name: Debian
      versions:
        - buster
  galaxy_tags:
    - networking
    - system
dependencies: []
