---
# Copyright (C) 2013-2018 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2015-2017 Robin Schneider <ypid@riseup.net>
# Copyright (C) 2014-2018 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

- name: Create ACME system group
  group:
    name: '{{ pki_acme_group }}'
    state: 'present'
    system: True

- name: Create ACME system account
  user:
    name: '{{ pki_acme_user }}'
    group: '{{ pki_acme_group }}'
    home: '{{ pki_acme_home }}'
    state: 'present'
    system: True
    createhome: False
    shell: '/bin/false'

- name: Install acme-tiny from source
  when: ansible_distribution_release in
        [ "wheezy", "jessie", "stretch",
          "precise", "trusty", "xenial", "bionic" ]
  block:

    - name: Create source directory
      file:
        path: '{{ pki_acme_tiny_src }}'
        state: 'directory'
        owner: 'root'
        group: 'root'
        mode: '0755'

    - name: Clone acme-tiny source code
      git:
        repo: '{{ pki_acme_tiny_repo }}'
        dest: '{{ pki_acme_tiny_src + "/acme-tiny" }}'
        version: '{{ pki_acme_tiny_version }}'

    - name: Install acme-tiny script
      file:
        path: '{{ pki_acme_tiny_bin }}'
        src: '{{ pki_acme_tiny_src }}/acme-tiny/acme_tiny.py'
        state: 'link'
        force: True  # Overwrite previously copied script
        mode: '0755'

- name: Create ACME challenge path
  file:
    path: '{{ pki_acme_challenge_dir | dirname }}'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'
  when: pki_create_acme_challenge_dir

- name: Create ACME challenge directory
  file:
    path: '{{ pki_acme_challenge_dir }}'
    state: 'directory'
    owner: '{{ pki_acme_user }}'
    group: '{{ pki_acme_group }}'
    mode: '0755'
  when: pki_create_acme_challenge_dir
