---
# Copyright (C) 2014-2019 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2015-2019 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

- name: Import DebOps secret role
  import_role:
    name: 'secret'

- include: configure_servers.yml
  when: boxbackup_server is defined and boxbackup_server == ansible_fqdn

- include: configure_clients.yml
  when: boxbackup_server is defined and boxbackup_server != ansible_fqdn
