---
# Copyright (C) 2016 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2016 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

# A separate handler is needed to ensure the correct order of execution
- name: Reload systemd daemon (gunicorn)
  systemd:
    daemon_reload: True
  when: ansible_service_mgr == 'systemd'

- name: Restart gunicorn
  service:
    name: 'gunicorn'
    state: 'restarted'

- name: Start Green Unicorn instances
  script: 'script/start-gunicorn-instances'
