---
# Copyright (C) 2018 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2018 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

# Ensure that custom Ansible plugins and modules included in the main DebOps
# collection are available to roles in other collections.
collections: [ 'debops.debops' ]

dependencies: []

galaxy_info:

  company: 'DebOps'
  author: 'Maciej Delmanowski'
  description: 'Install Ansible on Debian/Ubuntu host using Ansible'
  license: 'GPL-3.0-only'
  min_ansible_version: '2.4.0'

  platforms:

    - name: Debian
      versions:
        - wheezy
        - jessie
        - stretch
        - buster

    - name: Ubuntu
      versions:
        - precise
        - trusty
        - xenial
        - bionic

  galaxy_tags:
    - ansible
