---
# Copyright (C) 2015 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2015 DebOps <http://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

- name: Import DebOps global handlers
  import_role:
    name: 'global_handlers'

- name: Install required packages
  package:
    name: '{{ q("flattened", fcgiwrap__packages) }}'
    state: 'present'
  register: fcgiwrap__register_install
  until: fcgiwrap__register_install is succeeded

- name: Check the fcgiwrap version
  environment:
    LC_MESSAGES: 'C'
  shell: "dpkg-query -W -f='${Version}\n' 'fcgiwrap'"
  register: fcgiwrap__register_version
  changed_when: False
  failed_when: False
  check_mode: False

- name: Make sure required system groups exist
  group:
    name:   '{{ item.group  | d(item.user) }}'
    system: '{{ item.system | d(True) }}'
    state: 'present'
  with_items: '{{ fcgiwrap__instances }}'
  when: fcgiwrap__instances and item.user | d(False)

- name: Make sure required system accounts exist
  user:
    name:       '{{ item.user }}'
    group:      '{{ item.group      | d(item.user) }}'
    shell:      '{{ item.shell      | d(omit) }}'
    home:       '{{ item.home       | d(omit) }}'
    createhome: '{{ item.createhome | d(False) }}'
    system:     '{{ item.system     | d(True) }}'
    state:      'present'
  with_items: '{{ fcgiwrap__instances }}'
  when: fcgiwrap__instances and item.user | d(False)

- name: Disable default fcgiwrap init script
  service:  # noqa no-handler
    name: 'fcgiwrap'
    state: 'stopped'
    enabled: False
  when: fcgiwrap__disable_default|bool and fcgiwrap__register_install is changed

- name: Configure fcgiwrap instances in sysvinit
  include: configure_sysvinit.yml
  when: ansible_service_mgr != 'systemd'

- name: Configure fcgiwrap instances in systemd
  include: configure_systemd.yml
  when: ansible_service_mgr == 'systemd'
