---
# handlers file for ansible-squid
- name: restart squid
  ansible.builtin.service:
    name: squid
    state: restarted
  become: true

- name: restart squid3
  ansible.builtin.service:
    name: squid3
    state: restarted
  become: true

- name: reload haproxy
  ansible.builtin.service:
    name: haproxy
    state: reloaded
  become: true

- name: restart haproxy
  ansible.builtin.service:
    name: haproxy
    state: restarted
  become: true

- name: reload ferm # noqa command-instead-of-module command-instead-of-shell
  ansible.builtin.shell: service ferm force-reload
  changed_when: false
  become: true
