---
# Copyright (C) 2015-2016 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2015-2016 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

- name: Configure network interfaces via ifupdown
  import_playbook: 'ifupdown.yml'

- name: Configure IPv6 Router Advertisement daemon
  import_playbook: 'radvd.yml'

- name: Configure ISC DHCP daemon
  import_playbook: 'dhcpd.yml'

- name: Configure unbound service
  import_playbook: 'unbound.yml'

- name: Configure DNSmasq service
  import_playbook: 'dnsmasq.yml'

- name: Configure Tinc VPN service
  import_playbook: 'tinc.yml'

- name: Configure ISC DHCP Relay service
  import_playbook: 'dhcrelay.yml'

- name: Configure DHCP Probe service
  import_playbook: 'dhcp_probe.yml'

- name: Configure SSL Tunnel service
  import_playbook: 'stunnel.yml'

- name: Configure keepalived service
  import_playbook: 'keepalived.yml'

- name: Configure Avahi service
  import_playbook: 'avahi.yml'
