---
# Copyright (C) 2021 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2021 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

- name: Refresh host facts
  action: 'setup'

- name: Reload systemd daemon
  systemd:
    daemon_reload: True
  listen:
    - 'Reload service manager'
  when: ansible_service_mgr == 'systemd'

- name: Create temporary files with systemd-tmpfiles
  command: 'systemd-tmpfiles --create'
  listen:
    - 'Create temporary files'
  when: ansible_service_mgr == 'systemd'
