---
# Copyright (C) 2017 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2017 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

- name: Restart mosquitto
  service:
    name: 'mosquitto'
    state: 'restarted'

- name: Reload mosquitto
  service:
    name: 'mosquitto'
    state: 'reloaded'
