---
# Copyright (C) 2014-2017 Maciej Delmanowski <drybjed@drybjed.net>
# Copyright (C) 2015-2017 Robin Schneider <ypid@riseup.net>
# Copyright (C) 2014-2017 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

- name: Test nginx and restart
  ansible.builtin.command: nginx -t
  register: nginx__register_check_restart
  changed_when: nginx__register_check_restart.changed | bool
  notify: [ 'Restart nginx' ]

- name: Test nginx and reload
  ansible.builtin.command: nginx -t
  register: nginx__register_check_reload
  changed_when: nginx__register_check_reload.changed | bool
  notify: [ 'Reload nginx' ]

- name: Restart nginx
  ansible.builtin.service:
    name: 'nginx'
    state: 'restarted'

- name: Reload nginx
  ansible.builtin.service:
    name: 'nginx'
    state: 'reloaded'
