---
# Copyright (C) 2017 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2017 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

- name: Check opendkim and restart
  command: opendkim -n
  notify: [ 'Restart opendkim' ]

- name: Check opendkim and reload
  command: opendkim -n
  notify: [ 'Reload opendkim' ]
  when: ansible_local|d() and ansible_local.opendkim|d() and
        ansible_local.opendkim.installed is defined and
        ansible_local.opendkim.installed | bool

- name: Restart opendkim
  service:
    name: 'opendkim'
    state: 'restarted'

- name: Reload opendkim
  service:
    name: 'opendkim'
    state: 'reloaded'
