---
# Copyright (C) 2022 CipherMail B.V. <https://www.ciphermail.com/>
# Copyright (C) 2022 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Restart opensearch
  ansible.builtin.service:
    name: 'opensearch'
    state: 'restarted'
