---
# Copyright (C) 2014-2017 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2014-2017 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

- name: Test radvd and restart
  command: radvd --configtest
  notify: [ 'Restart radvd' ]

- name: Restart radvd
  service:
    name: 'radvd'
    state: 'restarted'
