---
# Copyright (C) 2019 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2019 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

- name: Apply static resolvconf configuration
  command: '/usr/local/lib/resolvconf-static'

- name: Refresh /etc/resolv.conf
  command: 'resolvconf -u'
