---
# Copyright (C) 2014-2019 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2015-2019 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

- name: Restart smstools
  service: name=smstools state=restarted

- name: Restart xinetd
  service: name=xinetd state=restarted

- name: Reload xinetd
  service: name=xinetd state=reloaded
