---
# Copyright (C) 2015 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2015 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

- name: Restart stunnel
  service:
    name: 'stunnel4'
    state: 'restarted'

- name: Reload stunnel
  service:
    name: 'stunnel4'
    state: 'reloaded'
