---
# Copyright (C) 2021 Dr. Serge Victor <https://dr.sergevictor.eu/>
# Copyright (C) 2021 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Check telegraf and restart
  ansible.builtin.command: '/usr/bin/telegraf --test --config /etc/telegraf/telegraf.conf --config-directory /etc/telegraf/telegraf.d'
  register: telegraf__register_config_test
  changed_when: telegraf__register_config_test.changed | bool
  notify: [ 'Restart telegraf' ]

- name: Restart telegraf
  ansible.builtin.service:
    name: "telegraf"
    state: "restarted"
