---
# Copyright (C) 2017 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2017 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

- name: Check unbound configuration and reload
  command: unbound-checkconf /etc/unbound/unbound.conf
  notify: [ 'Reload unbound' ]

- name: Reload unbound
  service:
    name: 'unbound'
    state: 'reloaded'
