# tasks file
---
- name: install dependencies
  apt:
    name: "{{ hostname_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - configuration
    - hostname
    - hostname-dependencies

- name: update the hostname - hostname module
  hostname:
    name: "{{ hostname_hostname if hostname_hostname_use_full else hostname_hostname_short }}"
    use: "{{ hostname_use_strategy | default(omit) }}"
  tags:
    - configuration
    - hostname
    - hostname-update-hostname

- name: update the hostname - /etc/hostname file
  template:
    src: etc/hostname.j2
    dest: /etc/hostname
    owner: root
    group: root
    mode: 0644
  tags:
    - configuration
    - hostname
    - hostname-update-hostname
    - hostname-update-hostname-file

- name: update the hostname - /etc/hosts file
  template:
    src: etc/hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
  tags:
    - configuration
    - hostname
    - hostname-update-hosts-file

- name: update the hostname/domain facts
  set_fact:
    ansible_domain: "{{ hostname_hostname.split('.', 1)[1] }}"
    ansible_fqdn: "{{ hostname_hostname }}"
  when: ansible_fqdn != hostname_hostname
  tags:
    - configuration
    - hostname
    - hostname-update-facts
