# tasks file
---
- block:

    - name: configure | find existing
      find:
        paths: "{{ netplan_conf_path }}"
        patterns: '*.yaml,*.yml'
      register: _netplan_existing_files

    - name: configure | remove existing
      file:
        path: "{{ item['path'] }}"
        state: absent
      with_items: "{{ _netplan_existing_files['files'] }}"
      when:
        - item['path'] != netplan_conf_path + '/' + netplan_conf_file
      notify: netplan generate config

  when: netplan_conf_purge | bool
  tags:
    - netplan-configure-purge

- name: configure | update
  template:
    src: etc/netplan/config.yaml.j2
    dest: "{{ netplan_conf_path }}/{{ netplan_conf_file }}"
    mode: 0644
  when: netplan_conf | length
  notify: netplan generate config
  tags:
    - netplan-configure-update
