# tasks file
---
- name: install | dependencies
  apt:
    name: "{{ netplan_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - netplan-install-dependencies

- name: install | additional
  apt:
    name: "{{ netplan_install }}"
    state: "{{ apt_install_state | default('latest') }}"
  tags:
    - netplan-install-additional
