download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/debops-debops-3.2.0.tar.gz
format_version: 1.0.0
name: debops
namespace: debops
server: https://galaxy.ansible.com/api/
signatures: []
version: 3.2.0
version_url: /api/v3/plugin/ansible/content/published/collections/index/debops/debops/versions/3.2.0/
