apt__distribution_repository_map:
  'Ubuntu': 'https://nexus3.cloud.lab/repository/ubuntu'

apt__ubuntu_sources:

  - name: 'ubuntu-release'
    comment: |
      See http://help.ubuntu.com/community/UpgradeNotes for how to upgrade to
      newer versions of the distribution.
    types: '{{ apt__archive_types }}'
    uri: '{{ apt__distribution_repository_map.Ubuntu | d() }}'
    suites:
      - '{{ apt__distribution_release }}'
    components: [ 'main' ]
    state: '{{ "present"
               if (apt__distribution == "Ubuntu")
               else "ignore" }}'

  - name: 'ubuntu-release'
    components: [ 'restricted' ]
    state: '{{ "present"
               if (apt__distribution == "Ubuntu" and
                   apt__nonfree | bool)
               else "ignore" }}'

  - name: 'ubuntu-release-updates'
    comment: |
      Major bug fix updates produced after the final release of the
      distribution.
    types: '{{ apt__archive_types }}'
    uri: '{{ apt__distribution_repository_map.Ubuntu | d() }}'
    suites:
      - '{{ apt__distribution_release + "-updates" }}'
    components: [ 'main' ]
    state: '{{ "present"
               if (apt__distribution == "Ubuntu" and
                   apt__distribution_version != "n/a")
               else "ignore" }}'

  - name: 'ubuntu-release-updates'
    components: [ 'restricted' ]
    state: '{{ "present"
               if (apt__distribution == "Ubuntu" and
                   apt__distribution_version != "n/a" and
                   apt__nonfree | bool)
               else "ignore" }}'

  - name: 'ubuntu-release-universe'
    comment: |
      N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu
      team. Also, please note that software in universe WILL NOT receive any
      review or updates from the Ubuntu security team.
    types: '{{ apt__archive_types }}'
    uri: '{{ apt__distribution_repository_map.Ubuntu | d() }}'
    suites:
      - '{{ apt__distribution_release }}'
      - '{{ apt__distribution_release + "-updates" }}'
    components: [ 'universe' ]
    state: '{{ "present"
               if (apt__distribution == "Ubuntu")
               else "ignore" }}'

  - name: 'ubuntu-release-multiverse'
    comment: |
      N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu
      team, and may not be under a free licence. Please satisfy yourself as to
      your rights to use the software. Also, please note that software in
      multiverse WILL NOT receive any review or updates from the Ubuntu
      security team.
    types: '{{ apt__archive_types }}'
    uri: '{{ apt__distribution_repository_map.Ubuntu | d() }}'
    suites:
      - '{{ apt__distribution_release }}'
      - '{{ apt__distribution_release + "-updates" }}'
    components: [ 'multiverse' ]
    state: '{{ "present"
               if (apt__distribution == "Ubuntu" and
                   apt__nonfree | bool)
               else "ignore" }}'

  - name: 'ubuntu-release-backports'
    comment: |
      N.B. software from this repository may not have been tested as
      extensively as that contained in the main release, although it includes
      newer versions of some applications which may provide useful features.
      Also, please note that software in backports WILL NOT receive any review
      or updates from the Ubuntu security team.
    types: '{{ apt__archive_types }}'
    uri: '{{ apt__distribution_repository_map.Ubuntu | d() }}'
    suites:
      - '{{ apt__distribution_release + "-backports" }}'
    components: [ 'main' ]
    state: '{{ "present"
               if (apt__distribution == "Ubuntu" and
                   apt__distribution_version != "n/a")
               else "ignore" }}'

  - name: 'ubuntu-release-backports'
    components: [ 'restricted' ]
    state: '{{ "present"
               if (apt__distribution == "Ubuntu" and
                   apt__distribution_version != "n/a" and
                   apt__nonfree | bool)
               else "ignore" }}'

  - name: 'ubuntu-release-backports'
    components: [ 'universe' ]
    state: '{{ "present"
               if (apt__distribution == "Ubuntu" and
                   apt__distribution_version != "n/a")
               else "ignore" }}'

  - name: 'ubuntu-release-backports'
    components: [ 'multiverse' ]
    state: '{{ "present"
               if (apt__distribution == "Ubuntu" and
                   apt__distribution_version != "n/a" and
                   apt__nonfree | bool)
               else "ignore" }}'

  - name: 'ubuntu-release-security'
    types: '{{ apt__archive_types }}'
    uri: '{{ apt__distribution_repository_map.Ubuntu | d() }}'
    suites:
      - '{{ apt__distribution_release + "-security" }}'
    components: [ 'main' ]
    separate: False
    state: '{{ "present"
               if (apt__distribution == "Ubuntu" and
                   apt__distribution_version != "n/a")
               else "ignore" }}'

  - name: 'ubuntu-release-security'
    components: [ 'restricted' ]
    separate: False
    state: '{{ "present"
               if (apt__distribution == "Ubuntu" and
                   apt__distribution_version != "n/a" and
                   apt__nonfree | bool)
               else "ignore" }}'

  - name: 'ubuntu-release-universe-security'
    types: '{{ apt__archive_types }}'
    uri: '{{ apt__distribution_repository_map.Ubuntu | d() }}'
    suites:
      - '{{ apt__distribution_release + "-security" }}'
    components: [ 'universe' ]
    separate: False
    state: '{{ "present"
               if (apt__distribution == "Ubuntu" and
                   apt__distribution_version != "n/a")
               else "ignore" }}'

  - name: 'ubuntu-release-multiverse-security'
    types: '{{ apt__archive_types }}'
    uri: '{{ apt__distribution_repository_map.Ubuntu | d() }}'
    suites:
      - '{{ apt__distribution_release + "-security" }}'
    components: [ 'multiverse' ]
    state: '{{ "present"
               if (apt__distribution == "Ubuntu" and
                   apt__distribution_version != "n/a" and
                   apt__nonfree | bool)
               else "ignore" }}'

apt__repositories:

  - name: 'ceph-v18'
    filename: 'ceph-v18.list'
    repo: 'deb https://nexus3.cloud.lab/repository/ceph/debian-reef/ {{ ansible_distribution_release }} main'
    signed_by: 'https://nexus3.cloud.lab/repository/ceph/keys/release.asc'
    state: '{{ "present"
               if (ansible_distribution == "Ubuntu" and 
                   ansible_distribution_release in ["focal", "jammy"] and
                   apt__distribution_version != "n/a")
               else "ignore" }}'

  - name: 'docker'
    filename: 'docker.list'
    repo: 'deb https://nexus3.cloud.lab/repository/docker/ubuntu {{ ansible_distribution_release }} stable'
    signed_by: 'https://nexus3.cloud.lab/repository/docker/ubuntu/gpg'
    state: '{{ "present"
               if (ansible_distribution == "Ubuntu" and
                   apt__distribution_version != "n/a")
               else "ignore" }}'

apt__configuration:

  - name: 'verify-peer'
    filename: '99verify-peer.conf'
    raw: |
      Acquire { https::Verify-Peer false }
    state: 'present'
