apt__distribution_repository_map:
  'Ubuntu': 'https://nexus3.cloud.lab/repository/ubuntu'

apt__sources:
  - name: 'ubuntu-release-partner'
    comment: |
      Uncomment the following two lines to add software from Canonical's
      'partner' repository.
      This software is not part of Ubuntu, but is offered by Canonical and the
      respective vendors as a service to Ubuntu users.
    types: '{{ apt__archive_types }}'
    uri: 'http://archive.canonical.com/ubuntu'
    suites:
      - '{{ apt__distribution_release }}'
    components: [ 'partner' ]
    state: 'absent'
  
apt__combined_sources: '{{ apt__ubuntu_sources
                           + apt__sources }}'

apt__repositories:
  - name: 'ceph-v18'
    filename: 'ceph-v18.list'
    repo: 'deb https://nexus3.cloud.lab/repository/ceph/debian-reef/ {{ ansible_distribution_release }} main'
    state: '{{ "present"
               if (ansible_distribution == "Ubuntu" and 
                   ansible_distribution_release in ["focal", "jammy"] and
                   apt__distribution_version != "n/a")
               else "ignore" }}'

apt__configuration:
  - name: 'verify-peer'
    filename: '99verify-peer.conf'
    raw: |
      Acquire { https::Verify-Peer false }
    state: 'present'
