---
# Copyright (C) 2017 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2017 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

# Ensure that custom Ansible plugins and modules included in the main DebOps
# collection are available to roles in other collections.
collections: [ 'debops.debops' ]

dependencies: []

galaxy_info:

  company: 'DebOps'
  author: 'Maciej Delmanowski'
  description: 'Manage kernel /sys filesystem using sysfsutils'
  license: 'GPL-3.0-only'
  min_ansible_version: '2.2.0'

  platforms:

    - name: Debian
      versions:
        - jessie
        - stretch

    - name: Ubuntu
      versions:
        - trusty
        - xenial

  galaxy_tags:
    - linux
    - kernel
    - hardware
