---
# Copyright (C) 2014-2016 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2016 Robin Schneider <ypid@riseup.net>
# Copyright (C) 2014-2016 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

# Ensure that custom Ansible plugins and modules included in the main DebOps
# collection are available to roles in other collections.
collections: [ 'debops.debops' ]

dependencies: []

galaxy_info:

  company: 'DebOps'
  author: 'Maciej Delmanowski, Robin Schneider'
  description: 'Manage service definitions in /etc/services'
  license: 'GPL-3.0-only'
  min_ansible_version: '2.0.0'

  platforms:

    - name: Ubuntu
      versions:
        - precise
        - quantal
        - raring
        - saucy
        - trusty

    - name: Debian
      versions:
        - wheezy
        - jessie

  galaxy_tags:
    - networking
    - system
