---
# Copyright (C) 2019-2023 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2019-2023 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

- name: Configure Filebeat service
  import_playbook: '../service/filebeat.yml'

- name: Configure Metricbeat service
  import_playbook: '../service/metricbeat.yml'

- name: Configure GitLab Runner service
  import_playbook: '../service/gitlab_runner.yml'

- name: Configure Telegraf service
  import_playbook: '../service/telegraf.yml'

- name: Configure Zabbix Agent
  import_playbook: '../service/zabbix_agent.yml'
