---
# Copyright (C) 2015-2023 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2015-2023 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

- name: Configure Hardware RAID monitoring
  import_playbook: '../service/hwraid.yml'

- name: Configure GRUB bootloader
  import_playbook: '../service/grub.yml'
