---
# Copyright (C) 2015-2023 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2015-2023 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

- name: Configure network interfaces via networkd
  import_playbook: '../service/networkd.yml'

- name: Configure network interfaces via ifupdown
  import_playbook: '../service/ifupdown.yml'

- name: Configure IPv6 Router Advertisement daemon
  import_playbook: '../service/radvd.yml'

- name: Configure ISC DHCP daemon
  import_playbook: '../service/dhcpd.yml'

- name: Configure NTP service
  import_playbook: '../service/ntp.yml'

- name: Configure unbound service
  import_playbook: '../service/unbound.yml'

- name: Configure DNSmasq service
  import_playbook: '../service/dnsmasq.yml'

- name: Configure Tinc VPN service
  import_playbook: '../service/tinc.yml'

- name: Configure ISC DHCP Relay service
  import_playbook: '../service/dhcrelay.yml'

- name: Configure DHCP Probe service
  import_playbook: '../service/dhcp_probe.yml'

- name: Configure SSL Tunnel service
  import_playbook: '../service/stunnel.yml'

- name: Configure keepalived service
  import_playbook: '../service/keepalived.yml'

- name: Configure Avahi service
  import_playbook: '../service/avahi.yml'
