---
# Copyright (C) 2015-2023 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2015-2023 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

- name: Configure /etc/aliases database
  import_playbook: '../service/etc_aliases.yml'

- name: Configure etesync service
  import_playbook: '../service/etesync.yml'

- name: Install HashiCorp applications
  import_playbook: '../service/hashicorp.yml'

- name: Configure APT-Cacher-NG service
  import_playbook: '../service/apt_cacher_ng.yml'

- name: Configure APT mirror service
  import_playbook: '../service/apt_mirror.yml'

- name: Configure docker-gen service
  import_playbook: '../service/docker_gen.yml'

- name: Configure gunicorn service
  import_playbook: '../service/gunicorn.yml'

- name: Configure Postfix SMTP server
  import_playbook: '../service/postfix.yml'

- name: Configure saslauthd service
  import_playbook: '../service/saslauthd.yml'

- name: Configure Dovecot IMAP/POP3 server
  import_playbook: '../service/dovecot.yml'

- name: Configure postscreen Postfix service
  import_playbook: '../service/postscreen.yml'

- name: Configure Postwhite Postfix service
  import_playbook: '../service/postwhite.yml'

- name: Manage Postfix service configuration
  import_playbook: '../service/postconf.yml'

- name: Configure Postfix LDAP support
  import_playbook: '../service/postldap.yml'

- name: Configure OpenDKIM service
  import_playbook: '../service/opendkim.yml'

- name: Configure Apache webserver
  import_playbook: '../service/apache.yml'

- name: Configure nginx webserver
  import_playbook: '../service/nginx.yml'

- name: Configure Mosquitto service
  import_playbook: '../service/mosquitto.yml'

- name: Configure SNMP daemon
  import_playbook: '../service/snmpd.yml'

- name: Configure Monit service
  import_playbook: '../service/monit.yml'

- name: Configure TFTP daemon
  import_playbook: '../service/tftpd.yml'

- name: Configure Samba service
  import_playbook: '../service/samba.yml'

- name: Configure TGT, userspace iSCSI client
  import_playbook: '../service/tgt.yml'

- name: Configure MariaDB/MySQL database
  import_playbook: '../service/mariadb_server.yml'

- name: Configure MariaDB/MySQL client
  import_playbook: '../service/mariadb.yml'

- name: Configure PostgreSQL service
  import_playbook: '../service/postgresql_server.yml'

- name: Configure PostgreSQL client
  import_playbook: '../service/postgresql.yml'

- name: Configure Elastic APT repositories
  import_playbook: '../service/elastic_co.yml'

- name: Configure Elasticsearch database
  import_playbook: '../service/elasticsearch.yml'

- name: Configure Kibana service
  import_playbook: '../service/kibana.yml'

- name: Configure InfluxData APT repositories
  import_playbook: '../service/influxdata.yml'

- name: Configure InfluxDB database
  import_playbook: '../service/influxdb_server.yml'

- name: Configure InfluxDB client
  import_playbook: '../service/influxdb.yml'

- name: Configure Icinga 2 service
  import_playbook: '../service/icinga.yml'

- name: Configure Icinga 2 database
  import_playbook: '../service/icinga_db.yml'

- name: Configure Icinga 2 Web frontend
  import_playbook: '../service/icinga_web.yml'

- name: Configure RabbitMQ service
  import_playbook: '../service/rabbitmq_server.yml'

- name: Configure RabbitMQ management webconsole
  import_playbook: '../service/rabbitmq_management.yml'

- name: Configure memcached service
  import_playbook: '../service/memcached.yml'

- name: Configure Redis database
  import_playbook: '../service/redis_server.yml'

- name: Configure Redis Sentinel service
  import_playbook: '../service/redis_sentinel.yml'

- name: Configure MinIO service
  import_playbook: '../service/minio.yml'

- name: Configure MinIO Client
  import_playbook: '../service/mcli.yml'

- name: Configure Docker Registry service
  import_playbook: '../service/docker_registry.yml'

- name: Configure reprepro APT repository
  import_playbook: '../service/reprepro.yml'

- name: Configure SMS Gateway service
  import_playbook: '../service/smstools.yml'

- name: Install Salt Master service
  import_playbook: '../service/salt.yml'

- name: Configure Fail2ban service
  import_playbook: '../service/fail2ban.yml'

- name: Configure Prosody XMPP server
  import_playbook: '../service/prosody.yml'

- name: Configure FreeRADIUS service
  import_playbook: '../service/freeradius.yml'

- name: Configure Tinyproxy service
  import_playbook: '../service/tinyproxy.yml'

- name: Configure libuser library
  import_playbook: '../service/libuser.yml'

- name: Configure MiniDLNA service
  import_playbook: '../service/minidlna.yml'

- name: Configure PowerDNS service
  import_playbook: '../service/pdns.yml'

- name: Configure BIND DNS server
  import_playbook: '../service/bind.yml'

- name: Configure rspamd service
  import_playbook: '../service/rspamd.yml'

- name: Configure OpenSearch database
  import_playbook: '../service/opensearch.yml'
