---
# Copyright (C) 2015-2023 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2015-2023 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

- name: Configure mount points
  import_playbook: '../service/mount.yml'

- name: Configure network information database
  import_playbook: '../service/netbase.yml'

- name: Configure sysnews service
  import_playbook: '../service/sysnews.yml'

- name: Configure kernel modules
  import_playbook: '../service/kmod.yml'

- name: Configure sysfs attributes
  import_playbook: '../service/sysfs.yml'

- name: Configure swap files
  import_playbook: '../service/swapfile.yml'

- name: Configure LVM subsystem
  import_playbook: '../service/lvm.yml'

- name: Configure NFS server service
  import_playbook: '../service/nfs_server.yml'

- name: Configure NFS client service
  import_playbook: '../service/nfs.yml'

- name: Configure gitusers environment
  import_playbook: '../service/gitusers.yml'

- name: Configure OpenLDAP service
  import_playbook: '../service/slapd.yml'

- name: Configure nslcd service
  import_playbook: '../service/nslcd.yml'

- name: Configure nscd service
  import_playbook: '../service/nscd.yml'

- name: Configure sssd service
  import_playbook: '../service/sssd.yml'

- name: Configure iSCSI devices
  import_playbook: '../service/iscsi.yml'

- name: Configure cryptsetup subsystem
  import_playbook: '../service/cryptsetup.yml'

- name: Configure QubesOS persistent paths
  import_playbook: '../service/persistent_paths.yml'

- name: Configure external APT repositories
  import_playbook: '../service/extrepo.yml'

- name: Configure NeuroDebian APT repository
  import_playbook: '../service/neurodebian.yml'

- name: Configure dropbear SSH server in initramfs
  import_playbook: '../service/dropbear_initramfs.yml'
