---
# Copyright (C) 2023 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2023 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

- name: Configure system and service manager
  import_playbook: '../service/systemd.yml'

- name: Configure system journal and log service
  import_playbook: '../service/journald.yml'

- name: Configure network manager service
  import_playbook: '../service/networkd.yml'

- name: Configure time synchronization service
  import_playbook: '../service/timesyncd.yml'

- name: Configure system resolver
  import_playbook: '../service/resolved.yml'
