---
# Copyright (C) 2015-2023 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2015-2023 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

- name: Configure LXC service
  import_playbook: '../service/lxc.yml'

- name: Configure LXD service
  import_playbook: '../service/lxd.yml'

- name: Configure Docker Engine service
  import_playbook: '../service/docker_server.yml'

- name: Configure libvirt daemon service
  import_playbook: '../service/libvirtd.yml'

- name: Configure libvirt qemu support
  import_playbook: '../service/libvirtd_qemu.yml'

- name: Configure libvirt client environment
  import_playbook: '../service/libvirt.yml'
