# tasks file
---
- name: install
  apt:
    name: "{{ timezone_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - configuration
    - timezone
    - timezone-install

- name: configure /etc/localtime
  file:
    src: /usr/share/zoneinfo/{{ timezone_zone }}
    dest: /etc/localtime
    state: link
    force: true
  tags:
    - configuration
    - timezone
    - timezone-configure-etc-localtime

- name: configure /etc/timezone
  template:
    src: "{{ timezone_etc_timezone.lstrip('/') }}.j2"
    dest: "{{ timezone_etc_timezone }}"
    owner: root
    group: root
    mode: 0644
  notify: update tzdata
  tags:
    - configuration
    - timezone
    - timezone-configure-etc-timezone
