---
- name: Certificate manage example
  hosts: ipaserver
  become: false
  gather_facts: false
  module_defaults:
    freeipa.ansible_freeipa.ipacert:
      ipaadmin_password: SomeADMINpassword
      ipaapi_context: client

  tasks:
  - name: Retrieve a certificate
    freeipa.ansible_freeipa.ipacert:
      serial_number: 12345
      state: retrieved
    register: cert_retrieved
