---
# Copyright (C) 2015-2020 Robin Schneider <ypid@riseup.net>
# Copyright (C) 2015-2020 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

# Ensure that custom Ansible plugins and modules included in the main DebOps
# collection are available to roles in other collections.
collections: [ 'debops.debops' ]

dependencies: []

galaxy_info:

  company: 'DebOps'
  author: 'Robin Schneider'
  description: 'Setup and manage encrypted filesystems'
  license: 'GPL-3.0-only'
  min_ansible_version: '2.2.3'

  platforms:

    - name: Ubuntu
      versions:
        - precise
        - quantal
        - raring
        - saucy
        - trusty

    - name: Debian
      versions:
        - wheezy
        - jessie
        - stretch

  galaxy_tags:
    - encryption
    - security
    - filesystem
    - cryptsetup
    - dmcrypt
    - luks
