# meta file
---
galaxy_info:
  author: oefenweb
  role_name: dns
  company: Oefenweb.nl B.V.
  description: Set up dns in Debian-like systems
  license: BSD
  min_ansible_version: 2.10.0
  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic
        - focal
    - name: Debian
      versions:
        - jessie
        - stretch
        - buster
  galaxy_tags:
    - system
    - networking
dependencies: []
