---
- name: Initialize operation system
  hosts: all
  tasks:
    - name: Add Ceph apt key
      ansible.builtin.get_url:
        url: "https://{{ repository_url }}/ceph/keys/release.asc"
        dest: /etc/apt/trusted.gpg.d/ceph.asc
        mode: '0644'
        force: true
      register: add_repository_key
      ignore_errors: true

    - name: Manage Advanced Package Manager
      import_role:
        name: debops.debops.apt
      tags: apt

    - name: Install APT packages
      import_role:
        name: debops.debops.apt_install
      tags: apt_install

    - name: Manage ca-certificates
      import_role:
        name: oefenweb.ca_certificates
      tags: ca_certificates

    - name: Manage Network Time Protocol service
      import_role:
        name: debops.debops.ntp
      tags: ntp

    - name: Configure localization and internationalization
      import_role:
        name: debops.debops.locales
      tags: locales

    - name: Manage time zone configuration
      import_role:
        name: debops.debops.tzdata
      tags: tzdata

    - name: Configure sudo service
      import_role:
        name: debops.debops.sudo
      tags: sudo

    - name: Manage SSH public keys
      import_role:
        name: debops.debops.authorized_keys
      tags: authorized_keys

    - name: Manage OpenSSH Server
      import_role:
        name: debops.debops.sshd
      tags: sshd

    - name: Configure log rotation
      import_role:
        name: debops.debops.logrotate
      tags: logrotate

    - name: Manage user and group accounts
      import_role:
        name: oefenweb.user
      tags: user

    - name: Set up vim
      import_role:
        name: oefenweb.vim
      tags: vim

    - name: Set up DNS
      import_role:
        name: oefenweb.dns
      tags: dns
      when: ansible_distribution == 'Debian'

    - name: Manage netplan configuration
      import_role:
        name: mrlesmithjr.netplan
      tags: netplan
      when: ansible_distribution == 'Ubuntu'
