---

- name: Manage Docker server
  hosts: docker
  remote_user: ansible
  become: True
  tasks:
    - name: Manage Docker server
      include_role:
        name: debops.debops.docker_server
      tags: docker_server
