---
- hosts: kubernetes
  remote_user: ansible
  become: True
  tasks:
    - name: Install packages
      apt:
        pkg:
        - ceph-common
        - conntrack
        - ebtables
        - ipset
        - ipvsadm
        - nfs-common
        - open-iscsi
        - socat
        - uidmap
        - xfsprogs
        update_cache: yes
        state: present
    - name: Make sure iscsid is running
      ansible.builtin.systemd:
        name: iscsid
        state: started
        enabled: yes
  roles:
    - role: containerd
      vars:
        containerd_repo: https://nexus3.cloud.lab/repository/docker/
        containerd_registry_mirrors:
          - name: docker.io
            endpoint:
              - https://registry.cloud.lab
          - name: quay.io
            endpoint:
              - https://registry.cloud.lab 
          - name: gcr.io
            endpoint:
              - https://registry.cloud.lab
          - name: registry.k8s.io
            endpoint:
              - https://registry.cloud.lab
