---

- name: Manage Docker server
  hosts: docker
  tasks:
    - name: Add Docker apt key
      ansible.builtin.get_url:
        url: "https://nexus3.cloud.lab/repository/docker/debian/gpg"
        dest: /etc/apt/trusted.gpg.d/docker.asc
        mode: '0644'
        force: true
      register: add_repository_key
      ignore_errors: true

    - name: Manage Advanced Package Manager
      include_role:
        name: debops.debops.apt
      tags: apt

    - name: Manage Docker server
      include_role:
        name: debops.debops.docker_server
      tags: docker_server
