---
- name: Manage Docker server
  hosts: docker
  tasks:
    - name: Include vars
      include_vars:
        file: '{{ inventory_dir }}/group_vars/all/vars.yml'

    - name: Manage Advanced Package Manager
      import_role:
        name: debops.debops.apt
      tags: apt

    - name: Manage Docker server
      import_role:
        name: debops.debops.docker_server
      tags: docker_server
