---
- hosts: rocky_k8s
  remote_user: rocky
  tasks:
    - name: Install a list of packages
      yum:
        name:
        - iscsi-initiator-utils
        - xfsprogs
        - socat
        - conntrack
        - ebtables
        - ipset
        - ipvsadm
        - nfs-utils
        update_cache: yes
        state: present
    - name: Make sure iscsid is running
      ansible.builtin.systemd:
        name: iscsid
        state: started
        enabled: yes
  roles:
    - role: chrony
    - role: containerd
      vars:
        containerd_repo: https://nexus3.cloud.lab/repository/docker-el/
        containerd_repo_address: https://nexus3.cloud.lab/repository/docker-el/centos/
        containerd_registry_mirrors:
          - name: docker.io
            endpoint:
              - https://registry-docker.cloud.lab
          - name: quay.io
            endpoint:
              - https://registry-quay.cloud.lab
          - name: gcr.io
            endpoint:
              - https://registry-k8s.cloud.lab
          - name: k8s.gcr.io
            endpoint:
              - https://registry-k8s.cloud.lab
          - name: registry.k8s.io
            endpoint:
              - https://registry-k8s.cloud.lab
