---
- name: Initialize Kubernetes adm system
  hosts: adm
  tasks:
    - name: Include vars
      include_vars:
        file: '{{ inventory_dir }}/group_vars/all/vars.yml'

    - name: Manage Advanced Package Manager
      import_role:
        name: debops.debops.apt
      tags: apt
  
    - name: Install APT packages
      import_role:
        name: debops.debops.apt_install
      tags: apt_install

    - name: Create the k8s completion file
      copy:
        content: |
          source <(kubectl completion bash)
        dest: /etc/profile.d/k8s_comletion.sh
        owner: 'root'
        group: 'root'
        mode: '0644'
