---
- name: Manage kubernetes server
  hosts: kubernetes
  tasks:
    - name: Install APT packages
      import_role:
        name: debops.debops.apt_install
      tags: apt_install

    - name: Create the k8s completion file
      copy:
        content: |
          source <(kubectl completion bash)
        dest: /etc/profile.d/k8s_comletion.sh
        owner: 'root'
        group: 'root'
        mode: '0644'

  roles:
    - role: containerd
      vars:
        containerd_repo: https://nexus3.cloud.lab/repository/docker/
        containerd_registry_mirrors:
          - name: docker.io
            endpoint:
              - https://registry.cloud.lab
          - name: quay.io
            endpoint:
              - https://registry.cloud.lab 
          - name: gcr.io
            endpoint:
              - https://registry.cloud.lab
          - name: registry.k8s.io
            endpoint:
              - https://registry.cloud.lab
          - name: ghcr.io
            endpoint:
              - https://registry.cloud.lab
