---
- hosts: ubuntu
  remote_user: ubuntu
  roles:
    - role: d_apt
      vars:
        apt_manage_sources_list: true
        apt_ubuntu_mirror: http://vm-data-20.cloud.lab:8081/repository/ubuntu/
        apt_ubuntu_security_mirror: http://vm-data-20.cloud.lab:8081/repository/ubuntu/
