---
- hosts: ubuntu
  roles:
    - role: apt
      vars:
        apt_manage_sources_list: true
        apt_ubuntu_mirror: http://vm-data-20.cloud.lab:8081/repository/ubuntu/
        apt_ubuntu_security_mirror: http://vm-data-20.cloud.lab:8081/repository/ubuntu/
    - role: ca_certificates
      vars:
        ca_certificates_certificate_map:
          - src: ca.crt
            dest: cloud.lab/ca.crt
    - role: sudoers
      vars:
        sudoers_sudoers:
          defaults:
            - env_reset
            - exempt_group=sudo
            - mail_badpass
            - secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
          privileges:
            - name: root
              entry: "ALL=(ALL:ALL) ALL"
            - name: "%admin"
              entry: "ALL=(ALL) ALL"
            - name: "%sudo"
              entry: "ALL=(ALL:ALL) NOPASSWD:ALL"
    - role: ssh_keys
      vars:
        ssh_keys_private_keys:
          - owner: ubuntu
            src: files/id_rsa
        ssh_keys_public_keys:
          - owner: ubuntu
            src: files/id_rsa.pub
        ssh_keys_authorized_keys:
          - owner: ubuntu
            src: files/id_rsa.pub
    - role: timezone
      vars:
        timezone_zone: Asia/Shanghai
    - role: chrony
