---
# Copyright (C) 2014-2019 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2015-2019 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

# Ensure that custom Ansible plugins and modules included in the main DebOps
# collection are available to roles in other collections.
collections: [ 'debops.debops' ]

dependencies: []

galaxy_info:

  company: 'DebOps'
  author: 'Maciej Delmanowski'
  description: 'Install and configure Samba file sharing server.'
  license: 'GPL-3.0-only'
  min_ansible_version: '1.9.0'

  platforms:

    - name: Debian
      versions:
        - wheezy
        - jessie

    - name: Ubuntu
      versions:
        - precise
        - quantal
        - raring
        - saucy
        - trusty

  galaxy_tags:
    - system
    - networking
