---
- name: Servicedelegationrule absent example
  hosts: ipaserver
  become: no

  tasks:
  - name: Ensure servicedelegationrule test-delegation-rule is absent
    freeipa.ansible_freeipa.ipaservicedelegationrule:
      ipaadmin_password: SomeADMINpassword
      name: test-delegation-rule
      state: absent
