---
# Copyright (C) 2015-2020 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2015-2020 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

- name: Update DebOps in the background with async
  become: '{{ controller__install_systemwide | bool }}'
  ansible.builtin.command: debops-update
  async: '{{ controller__async_timeout | int }}'
  poll: 0
  register: controller__register_update_async
  changed_when: controller__register_update_async.changed | bool
  when: not controller__update_method == 'sync'

- name: Update DebOps in the background with batch
  become: '{{ controller__install_systemwide | bool }}'
  ansible.builtin.shell: |
    set -o nounset -o pipefail -o errexit &&
    type debops-update > /dev/null 2>&1 && (echo 'debops-update' | batch > /dev/null 2>&1) || true
  args:
    executable: 'bash'
  register: controller__register_update_batch
  changed_when: controller__register_update_batch.changed | bool
  when: (not controller__update_method == 'sync' and
         (ansible_local | d() and ansible_local.atd | d() and
          ansible_local.atd.enabled | bool))
