---
# Copyright (C) 2014-2019 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2019      Alin Alexandru <alin.alexandru@innobyte.com>
# Copyright (C) 2015-2019 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

- name: Import DebOps secret role
  import_role:
    name: 'secret'

- include: phpipam.yml
  when: phpipam__mode is defined and 'webui' in phpipam__mode

- include: phpipam-scripts.yml
  when: phpipam__mode is defined and 'scripts' in phpipam__mode
