---
# Copyright (C) 2015-2016 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2015-2016 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

- name: Configure /etc/aliases database
  import_playbook: 'etc_aliases.yml'

- name: Configure etesync service
  import_playbook: 'etesync.yml'

- name: Install HashiCorp applications
  import_playbook: 'hashicorp.yml'

- name: Configure APT-Cacher-NG service
  import_playbook: 'apt_cacher_ng.yml'

- name: Configure docker-gen service
  import_playbook: 'docker_gen.yml'

- name: Configure gunicorn service
  import_playbook: 'gunicorn.yml'

- name: Configure Postfix SMTP server
  import_playbook: 'postfix.yml'

- name: Configure saslauthd service
  import_playbook: 'saslauthd.yml'

- name: Configure Dovecot IMAP/POP3 server
  import_playbook: 'dovecot.yml'

- name: Configure postscreen Postfix service
  import_playbook: 'postscreen.yml'

- name: Configure Postwhite Postfix service
  import_playbook: 'postwhite.yml'

- name: Manage Postfix service configuration
  import_playbook: 'postconf.yml'

- name: Configure Postfix LDAP support
  import_playbook: 'postldap.yml'

- name: Configure OpenDKIM service
  import_playbook: 'opendkim.yml'

- name: Configure Apache webserver
  import_playbook: 'apache.yml'

- name: Configure nginx webserver
  import_playbook: 'nginx.yml'

- name: Configure Mosquitto service
  import_playbook: 'mosquitto.yml'

- name: Configure SNMP daemon
  import_playbook: 'snmpd.yml'

- name: Configure Monit service
  import_playbook: 'monit.yml'

- name: Configure TFTP daemon
  import_playbook: 'tftpd.yml'

- name: Configure Samba service
  import_playbook: 'samba.yml'

- name: Configure TGT, userspace iSCSI client
  import_playbook: 'tgt.yml'

- name: Configure MariaDB/MySQL database
  import_playbook: 'mariadb_server.yml'

- name: Configure MariaDB/MySQL client
  import_playbook: 'mariadb.yml'

- name: Configure PostgreSQL service
  import_playbook: 'postgresql_server.yml'

- name: Configure PostgreSQL client
  import_playbook: 'postgresql.yml'

- name: Configure Elastic APT repositories
  import_playbook: 'elastic_co.yml'

- name: Configure Elasticsearch database
  import_playbook: 'elasticsearch.yml'

- name: Configure Kibana service
  import_playbook: 'kibana.yml'

- name: Configure InfluxData APT repositories
  import_playbook: 'influxdata.yml'

- name: Configure InfluxDB database
  import_playbook: 'influxdb_server.yml'

- name: Configure InfluxDB client
  import_playbook: 'influxdb.yml'

- name: Configure Icinga 2 service
  import_playbook: 'icinga.yml'

- name: Configure Icinga 2 database
  import_playbook: 'icinga_db.yml'

- name: Configure Icinga 2 Web frontend
  import_playbook: 'icinga_web.yml'

- name: Configure RabbitMQ service
  import_playbook: 'rabbitmq_server.yml'

- name: Configure RabbitMQ management webconsole
  import_playbook: 'rabbitmq_management.yml'

- name: Configure memcached service
  import_playbook: 'memcached.yml'

- name: Configure Redis database
  import_playbook: 'redis_server.yml'

- name: Configure Redis Sentinel service
  import_playbook: 'redis_sentinel.yml'

- name: Configure MinIO service
  import_playbook: 'minio.yml'

- name: Configure MinIO Client
  import_playbook: 'mcli.yml'

- name: Configure Docker Registry service
  import_playbook: 'docker_registry.yml'

- name: Configure reprepro APT repository
  import_playbook: 'reprepro.yml'

- name: Configure SMS Gateway service
  import_playbook: 'smstools.yml'

- name: Install Salt Master service
  import_playbook: 'salt.yml'

- name: Configure Fail2ban service
  import_playbook: 'fail2ban.yml'

- name: Configure Prosody XMPP server
  import_playbook: 'prosody.yml'

- name: Configure FreeRADIUS service
  import_playbook: 'freeradius.yml'

- name: Configure Tinyproxy service
  import_playbook: 'tinyproxy.yml'

- name: Configure libuser library
  import_playbook: 'libuser.yml'

- name: Configure MiniDLNA service
  import_playbook: 'minidlna.yml'

- name: Configure PowerDNS service
  import_playbook: 'pdns.yml'

- name: Configure rspamd service
  import_playbook: 'rspamd.yml'

- name: Configure OpenSearch database
  import_playbook: 'opensearch.yml'
