---
# Copyright (C) 2014-2019 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2015-2019 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

- name: Restart boxbackup-server
  service: name=boxbackup-server state=restarted

- name: Restart boxbackup-client
  service: name=boxbackup-client state=restarted
