---
# Copyright (C) 2017 Fabio Bonelli <fb@fabiobonelli.it>
# Copyright (C) 2017 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

# Ensure that custom Ansible plugins and modules included in the main DebOps
# collection are available to roles in other collections.
collections: [ 'debops.debops' ]

dependencies: []

galaxy_info:

  company: 'DebOps'
  author: 'Fabio Bonelli'
  description: 'Manage the root account'
  license: 'GPL-3.0-only'
  min_ansible_version: '2.2.0'

  platforms:

    - name: Debian
      versions:
        - jessie
        - stretch

    - name: Ubuntu
      versions:
        - xenial
        - yakkety

  galaxy_tags:
    - system
